/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* mUART_rx */
#define mUART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define mUART_rx_0_INBUF_ENABLED 1u
#define mUART_rx_0_INIT_DRIVESTATE 1u
#define mUART_rx_0_INIT_MUXSEL 18u
#define mUART_rx_0_INPUT_SYNC 2u
#define mUART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mUART_rx_0_NUM 4u
#define mUART_rx_0_PORT GPIO_PRT6
#define mUART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mUART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mUART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define mUART_rx_INBUF_ENABLED 1u
#define mUART_rx_INIT_DRIVESTATE 1u
#define mUART_rx_INIT_MUXSEL 18u
#define mUART_rx_INPUT_SYNC 2u
#define mUART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mUART_rx_NUM 4u
#define mUART_rx_PORT GPIO_PRT6
#define mUART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define mUART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mUART_tx */
#define mUART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mUART_tx_0_INBUF_ENABLED 0u
#define mUART_tx_0_INIT_DRIVESTATE 1u
#define mUART_tx_0_INIT_MUXSEL 18u
#define mUART_tx_0_INPUT_SYNC 2u
#define mUART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mUART_tx_0_NUM 5u
#define mUART_tx_0_PORT GPIO_PRT6
#define mUART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mUART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mUART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mUART_tx_INBUF_ENABLED 0u
#define mUART_tx_INIT_DRIVESTATE 1u
#define mUART_tx_INIT_MUXSEL 18u
#define mUART_tx_INPUT_SYNC 2u
#define mUART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mUART_tx_NUM 5u
#define mUART_tx_PORT GPIO_PRT6
#define mUART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define mUART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
